# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7e39daad5209691350b8a098f380b9e83f49babda825bfd8d199f6e025ed0fde5bf352ce0df61c5b31d5d45647ba76c10a58c38f7165cb25fe9d465efc07b62

test:
  secret_key_base: f83d45bd168d2a86596c37ab9a77ef09cdb8245af5c587517418f25e6db7fbe087c1d5c839c6857cff7c1fd51c11f6b9ed1db6b93ed5b5767b7368b962816a66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
